# .gitlab-ci.yml
stages:
  - build
  - deploy

build:
  stage: build
  image: node:latest
  script:
    - npm install --verbose
    - npm run build
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  image: alpine:latest
  script:
    # - rm -r public
    - mv ./dist ./public
  artifacts:
    paths:
      - public