# .gitlab-ci.yml
stages:
  - build
  - deploy

web:build:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
    - echo '/* /index.html 200' > dist/_redirects
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  image: alpine:latest
  script:
    - rm -r public
    - mv ./dist ./public
  artifacts:
    paths:
      - public